version: 0.2

env:
  variables:
    storeId: "myStoreId"
phases:
  pre_build:
    commands:
      - cd app/src/main/java/com/bikayi/apps
      - mv mydemoapp mydemoapp2
      - cd "$OLDPWD"
      - cd app/src/test/java/com/bikayi/apps
      - mv mydemoapp mydemoapp2
      - cd "$OLDPWD"
      - cd app/src/androidTest/java/com/bikayi/apps
      - mv mydemoapp mydemoapp2
      - cd "$OLDPWD"
      - cd app/src/main
      - sed -i 's/mydemoapp/mydemoapp2/g' AndroidManifest.xml
      - cd "$OLDPWD"
      - cd app/src/main/java/com/bikayi/apps/mydemoapp2
      - find ./ -type f -readable -writable -exec sed -i "s/mydemoapp/mydemoapp2/g" {} \;
      - cd "$OLDPWD"
      - cd app/src/test/java/com/bikayi/apps/mydemoapp2
      - find ./ -type f -readable -writable -exec sed -i "s/mydemoapp/mydemoapp2/g" {} \;
      - cd "$OLDPWD"
      - cd app/src/androidTest/java/com/bikayi/apps/mydemoapp2
      - find ./ -type f -readable -writable -exec sed -i "s/mydemoapp/mydemoapp2/g" {} \;
      - cd "$OLDPWD"
      - cd app/src/main/res/values
      - sed -i 's/MyDemoApp/MyDemoApp2/g' strings.xml
      - cd "$OLDPWD"
      - cd app
      - sed -i 's/mydemoapp/mydemoapp2/g' build.gradle
      - cd "$OLDPWD"
  build:
    commands:
      - chmod  777 script.sh && ./script.sh
      - chmod +x gradlew
      - ./gradlew assembleRelease
      - mkdir output
      - cd output
      - mkdir $storeId
      - cd "$OLDPWD"
      - cp app/build/outputs/apk/release/app-release-unsigned.apk output/$storeId/app-release-unsigned.apk
      - cp my-key.jks output/$storeId/my-key.jks
artifacts:
  files:
    - '**/*'
  base-directory: 'output'
