version: 0.2

phases:
  build:
    commands:
      - sudo apt-get install sudo -y
      - sudo apt-get install -y zipalign
      - zipalign -v -p 4 app-release-unsigned.apk my-app-unsigned-aligned.apk
