version: 0.2

phases:
  pre_build:
    commands:
      - ls
      - cd app/src/main/java/com/bikayi/apps
      - mv mydemoapp mydemoapp2
      - cd
      - ls
      - cd app/src/test/java/com/bikayi/apps
      - mv mydemoapp mydemoapp2
      - cd
      - cd app/src/androidTest/java/com/bikayi/apps
      - mv mydemoapp mydemoapp2
      - cd
      - cd app/src/main
      - sed -i 's/mydemoapp/mydemoapp2/g' AndroidManifest.xml
      - cd
      - cd app/src/main/java/com/bikayi/apps/mydemoapp2
      - find ./ -type f -readable -writable -exec sed -i "s/mydemoapp/mydemoapp2/g" {} \;
      - cd
      - cd app/src/test/java/com/bikayi/apps/mydemoapp2
      - find ./ -type f -readable -writable -exec sed -i "s/mydemoapp/mydemoapp2/g" {} \;
      - cd
      - cd app/src/androidTest/java/com/bikayi/apps/mydemoapp2
      - find ./ -type f -readable -writable -exec sed -i "s/mydemoapp/mydemoapp2/g" {} \;
      - cd
      - cd app/src/main/res/values
      - sed -i 's/MyDemoApp/MyDemoApp2/g' strings.xml
      - cd
      - cd app
      - sed -i 's/mydemoapp/mydemoapp2/g' build.gradle
      - cd
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew assembleRelease
      - cd app/build/outputs/apk/release
      - ls
      - zipalign -v -p 4 app-release-unsigned.apk my-app-unsigned-aligned.apk
artifacts:
  files:
    - '**/*'
