version: 0.2

phases:
  build:
    commands:
      - keytool -genkey -v -keystore my-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias my-alias
      - '123456'
      - '123456'
      - zipalign -v -p 4 app-release-unsigned.apk my-app-unsigned-aligned.apk
