version: 0.2

phases:
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew assembleRelease
      - cd app/build/outputs/apk/release
      - ls
      - zipalign -v -p 4 app-release-unsigned.apk my-app-unsigned-aligned.apk
artifacts:
  files:
    - '**/*'
