version: 0.2

env:
  variables:
    storeId: "myStoreId"
phases:
  pre_build:
    commands:
      - cd app/src/main/java/com/bikayi/apps
      - mv mydemoapp mydemoapp2
      - cd "$OLDPWD"
      - grep -rl mydemoapp . | xargs sed -i "" -e 's/mydemoapp/mydemoapp2/g'
      - grep -rl MyDemoApp . | xargs sed -i "" -e 's/MyDemoApp/MyDemoApp2/g'
      - cd "$OLDPWD"
  build:
    commands:
      - keytool -genkeypair -dname "cn=Sachin, ou=EnggTeam, o=Bikayi, c=IN" -alias my-alias -keypass 123456 -keystore my-key.jks -keyalg DSA -storepass 123456 -validity 10000
      - chmod +x gradlew
      - ./gradlew assembleRelease
      - mkdir output
      - cd output
      - mkdir $storeId
      - cd "$OLDPWD"
      - cp app/build/outputs/apk/release/app-release-unsigned.apk output/$storeId/app-release-unsigned.apk
      - cp my-key.jks output/$storeId/my-key.jks
artifacts:
  files:
    - '**/*'
  base-directory: 'output'
