version: 0.2

env:
  variables:
    storeId: "myStoreId"
phases:
  pre_build:
    commands:
      - cd app/src/main/java/com/bikayi/apps
      - mv mydemoapp mydemoapp2
      - cd "$OLDPWD"
      - grep -rl mydemoapp . | xargs sed -i 's/mydemoapp/mydemoapp2/g'
      - grep -rl MyDemoApp . | xargs sed -i 's/MyDemoApp/MyDemoApp2/g'
  build:
    commands:
      - chmod 777 script.sh && ./script.sh
      - chmod +x gradlew
      - ./gradlew assembleRelease
      - mkdir output
      - cd output
      - mkdir $storeId
      - cd "$OLDPWD"
      - cp app/build/outputs/apk/release/app-release-unsigned.apk output/$storeId/app-release-unsigned.apk
      - cp my-key.jks output/$storeId/my-key.jks
      - aws configure set default.s3.signature_version s3v4
artifacts:
  files:
    - '**/*'
  base-directory: 'output'
