version: 0.2

env:
  variables:
    storeId: "myStoreId"
    packageName: "demo2"
    appName: "Demo2"
phases:
  pre_build:
    commands:
      - cd app/src/main/java/com/bikayi/apps
      - mv mydemoapp $packageName
      - cd "$OLDPWD"
      - cd app/src/test/java/com/bikayi/apps
      - mv mydemoapp mydemoapp2
      - cd "$OLDPWD"
      - cd app/src/androidTest/java/com/bikayi/apps
      - mv mydemoapp mydemoapp2
      - cd "$OLDPWD"
      - grep -rl mydemoapp . | xargs sed -i 's/mydemoapp/$packageName/g'
      - grep -rl MyDemoApp . | xargs sed -i 's/MyDemoApp/$appName/g'
  build:
    commands:
      - chmod 777 script.sh && ./script.sh
      - chmod +x gradlew
      - ./gradlew assembleRelease
      - mkdir output
      - cd output
      - mkdir $storeId
      - cd "$OLDPWD"
      - cp app/build/outputs/apk/release/app-release-unsigned.apk output/$storeId/app-release-unsigned.apk
      - cp my-key.jks output/$storeId/my-key.jks
  artifacts:
    files:
      - '**/*'
    base-directory: 'output'
